#!/usr/bin/env python3
"""Rebuild every generated page from the book pages' own frontmatter.

Every book in `docs/` carries its state as frontmatter fields, not prose:

    ---
    title: "Atomic Habits"
    description: "An Easy & Proven Way to Build Good Habits & Break Bad Ones"
    author: "James Clear"
    narrator: "James Clear"
    format: audiobook
    shelf: read
    read_years: [2025]
    rating: 5
    tags: [Psychology, "Self-improvement"]
    ---

This script reads all of them and rewrites everything that lists or displays
them: each book page's own heading and metadata card, the shelf pages
(`index.md` "Currently reading", `want-to-read.md`, `previously-read/index.md`),
the `nav` table in `zensical.toml`, and the tag checkboxes in the "Add a book"
issue form. So marking a book as read is a frontmatter edit to that book's own
page: everything else follows from it.

Two fields are deliberately named the way they are:

- `shelf`, not `status` — Zensical reads `status` from a page's frontmatter as
  its *nav status marker* and stamps an icon next to the page in the sidebar
  (`partials/nav-item.html`), which is not what a reading shelf means.
- `icon`, which Zensical *does* read, is generated here on purpose so each book
  shows its format icon in the sidebar.

Tags are Zensical's own: the theme renders `tags:` as chips at the foot of the
page. The vocabulary lives in `[project.extra.tags]` in `zensical.toml` and is
validated from there, so there is no tags page for this script to generate.

Usage: python3 scripts/shelves.py [--check]
"""

from __future__ import annotations

import argparse
import json
import re
import sys
import tomllib
from dataclasses import dataclass, field
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DOCS = ROOT / "docs"
PREVIOUSLY_READ = DOCS / "previously-read"
LEGACY_TAGS = DOCS / "tags"
CONFIG = ROOT / "zensical.toml"
ISSUE_FORM = ROOT / ".github" / "ISSUE_TEMPLATE" / "add-book.yml"

SHELF_PAGES = {"index.md", "want-to-read.md"}

READING = "reading"
READ = "read"
WANT = "want"
SHELVES = {READING, READ, WANT}

SHELF_ICON = {READING: "lucide/book-marked", READ: "lucide/book", WANT: "lucide/book-plus"}
# What a shelf is called on a book's own page ("Read" is completed by its years,
# as in "Read in 2026"), and what the shelf's own page and nav section are called.
SHELF_LABEL = {READING: "Currently reading", READ: "Read", WANT: "Want to read"}
SHELF_PAGE = {READING: "Currently reading", READ: "Previously read", WANT: "Want to read"}

FORMAT_ICON = {"audiobook": "lucide/headphones", "physical": "lucide/book-open"}
FORMAT_LABEL = {"audiobook": "Audiobook", "physical": "Physical"}

AUTHOR_ICON = "lucide/user-round"
STAR_FULL = "material/star"
STAR_EMPTY = "material/star-outline"

FRONTMATTER = re.compile(r"\A---\n(.*?)\n---\n", re.DOTALL)
MARKDOWN_SPECIAL = re.compile(r"([*_\[\]`])")
# Captures greedily to the end of the line; the value is stripped by the caller.
FIELD = re.compile(r"^(\w+):(.*)$")

# Where the generated part of a book page stops and the reader's own notes
# begin. The marker is written into every book page, so it says so in the file.
# A page that has no marker yet is one somebody just hand-wrote as frontmatter
# and notes — all of its body is notes, and this run puts the marker in.
NOTES_MARKER = "<!-- Notes below. Everything above is generated by scripts/shelves.py. -->"

NO_NOTES = "*No thoughts written yet.*\n"

# The generated span of tag checkboxes in the "Add a book" issue form.
FORM_TAGS = re.compile(
    r"( *)# tags: generated by scripts/shelves\.py\n.*?^ *# end tags\n",
    re.DOTALL | re.MULTILINE,
)


def icon(name: str, tooltip: str = "") -> str:
    """An inline icon, optionally labelled for `content.tooltips` on hover."""
    shortcode = ":" + name.replace("/", "-") + ":"
    return f'{shortcode}{{ title="{tooltip}" }}' if tooltip else shortcode


@dataclass
class Book:
    slug: str
    title: str
    subtitle: str
    author: str
    narrator: str
    format: str  # "audiobook" | "physical" | ""
    shelf: str
    years: list[int]
    rating: int = 0
    tags: list[str] = field(default_factory=list)
    notes: str = NO_NOTES

    @property
    def sort_key(self) -> str:
        return self.title.lower()

    @property
    def format_label(self) -> str:
        return FORMAT_LABEL.get(self.format, "")

    @property
    def icon(self) -> str:
        """The icon that stands for this book: its format, or else its shelf."""
        return FORMAT_ICON.get(self.format) or SHELF_ICON[self.shelf]

    def shelf_text(self) -> str:
        if self.shelf == READ:
            return "Read in " + ", ".join(str(year) for year in self.years)
        return SHELF_LABEL[self.shelf]

    def heading_icon(self) -> str:
        return icon(SHELF_ICON[self.shelf], self.shelf_text())

    def title_link(self, prefix: str = "") -> str:
        return f"[{markdown_escape(self.title)}]({prefix}{self.slug}.md)"

    def author_line(self) -> str:
        return f"{icon(AUTHOR_ICON, 'Author')} {markdown_escape(self.author)}"

    def format_line(self) -> str:
        """The format icon, labelled — carrying the narrator when there is one."""
        if not self.format:
            return ""
        name = FORMAT_ICON[self.format]
        if self.narrator:
            tooltip = f"{self.format_label}, narrated by"
            return f"{icon(name, tooltip)} {markdown_escape(self.narrator)}"
        return f"{icon(name, 'Format')} {self.format_label}"

    def rating_line(self) -> str:
        """Five stars, `self.rating` of them filled, labelled on the first."""
        if not self.rating:
            return ""
        stars = [icon(STAR_FULL, f"Rated {self.rating} out of 5")]
        stars += [icon(STAR_FULL)] * (self.rating - 1)
        stars += [icon(STAR_EMPTY)] * (5 - self.rating)
        return " ".join(stars)

    def card(self, prefix: str = "", subtitle: bool = False, narrator: bool = False,
             rating: bool = False, rule: bool = False) -> str:
        """The book as one card in a `.grid.cards` list.

        `rule` splits the title off from the details with a horizontal rule,
        which suits a handful of roomy cards. Without it the details hang
        straight off the title on their own lines, which is what a shelf of a
        hundred books wants — the rule's margins would triple the page.
        """
        body = []
        if subtitle and self.subtitle:
            body.append(f"*{markdown_escape(self.subtitle)}*")
        body.append(self.author_line())
        if narrator and self.narrator:
            body.append(self.format_line())
        if rating and self.rating:
            body.append(self.rating_line())

        head = (f"{icon(self.icon, self.format_label or self.shelf_text())} "
                f"**{self.title_link(prefix)}**")
        if rule:
            paragraphs = [head, "---"] + body
            return "-   " + "\n\n    ".join(paragraphs)
        return "-   " + "<br>\n    ".join([head] + body)


def markdown_escape(value: str) -> str:
    """Keep punctuation literal inside heading/link text that markdown would parse."""
    return MARKDOWN_SPECIAL.sub(r"\\\1", value)


def unquote(value: str) -> str:
    """Read a YAML scalar: double-quoted values may carry escapes like \\u00e9."""
    if len(value) > 1 and value[0] == value[-1] == '"':
        try:
            return json.loads(value)
        except json.JSONDecodeError:
            return value[1:-1]
    if len(value) > 1 and value[0] == value[-1] == "'":
        return value[1:-1].replace("''", "'")
    return value


def parse_list(value: str) -> list[str]:
    """Read a flow-style YAML list: `[a, "b c", d]`. Empty for `[]` or a bare scalar."""
    inner = value.strip()
    if not (inner.startswith("[") and inner.endswith("]")):
        return []
    inner = inner[1:-1].strip()
    if not inner:
        return []
    return [unquote(item.strip()) for item in inner.split(",")]


def quote_list(values: list[str]) -> str:
    """Write a flow-style YAML list. Tag names carry spaces, so quote them all."""
    return "[" + ", ".join(json.dumps(value) for value in values) + "]"


def fail(message: str) -> None:
    print(f"error: {message}", file=sys.stderr)
    sys.exit(1)


def vocabulary() -> dict[str, str]:
    """The tag vocabulary, read from `[project.extra.tags]` in `zensical.toml`.

    Zensical uses this table to give each tag chip its icon; this script uses it
    as the list of tags a book is allowed to carry, so the two cannot drift.
    """
    config = tomllib.loads(CONFIG.read_text(encoding="utf-8"))
    tags = config.get("project", {}).get("extra", {}).get("tags", {})
    if not tags:
        fail("zensical.toml has no [project.extra.tags] — the tag vocabulary is empty")
    icons = config.get("project", {}).get("theme", {}).get("icon", {}).get("tag", {})
    for tag, identifier in sorted(tags.items()):
        if identifier not in icons:
            fail(f"tag {tag!r} maps to {identifier!r}, which has no "
                 f"[project.theme.icon.tag] entry")
    return tags


def book_pages() -> list[Path]:
    """Every page in `docs/` that is a book — one URL per book, at the site root.

    A page counts as a book when its frontmatter has a `shelf` field.
    """
    pages = []
    for path in sorted(DOCS.glob("*.md")):
        if path.name in SHELF_PAGES:
            continue
        frontmatter = FRONTMATTER.match(path.read_text(encoding="utf-8"))
        if frontmatter and re.search(r"^shelf:", frontmatter.group(1), re.MULTILINE):
            pages.append(path)
    return pages


def parse_frontmatter(block: str) -> dict[str, str | list[str]]:
    """Read the `key: value` lines of a frontmatter block. Flow lists stay lists."""
    meta: dict[str, str | list[str]] = {}
    for line in block.splitlines():
        matched = FIELD.match(line)
        if not matched:
            continue
        key, raw_value = matched.group(1), matched.group(2).strip()
        meta[key] = parse_list(raw_value) if raw_value.startswith("[") else unquote(raw_value)
    return meta


def validate(rel: Path, meta: dict, years: list[int], rating: int,
             tags_allowed: dict[str, str]) -> None:
    """Everything a book's frontmatter has to get right, in one place.

    This is what `--check` enforces on every pull request, so each failure names
    the file, the field, and what would have been acceptable instead.
    """
    if "title" not in meta:
        fail(f"{rel}: frontmatter has no title")
    if not meta.get("author"):
        fail(f"{rel}: frontmatter has no author")

    shelf = meta.get("shelf", "")
    if shelf not in SHELVES:
        fail(f"{rel}: shelf must be one of {sorted(SHELVES)}, got {shelf!r}")

    book_format = meta.get("format", "")
    if book_format and book_format not in FORMAT_ICON:
        fail(f"{rel}: format must be one of {sorted(FORMAT_ICON)}, got {book_format!r}")

    if shelf == READ and not years:
        fail(f"{rel}: shelf is read but read_years is empty")
    if shelf != READ and years:
        fail(f"{rel}: read_years is set but shelf is not read")

    if rating and not 1 <= rating <= 5:
        fail(f"{rel}: rating must be between 1 and 5, got {rating}")

    for tag in meta.get("tags", []):
        if tag not in tags_allowed:
            fail(f"{rel}: tag {tag!r} is not in the vocabulary — add it to "
                 f"[project.extra.tags] in zensical.toml, or use one of "
                 f"{sorted(tags_allowed)}")


def parse_book(path: Path, tags_allowed: dict[str, str]) -> Book:
    text = path.read_text(encoding="utf-8")

    frontmatter = FRONTMATTER.match(text)
    if not frontmatter:
        fail(f"{path.relative_to(ROOT)}: missing frontmatter")

    meta = parse_frontmatter(frontmatter.group(1))
    if not isinstance(meta.get("tags", []), list):
        meta["tags"] = []

    years_raw = meta.get("read_years", [])
    years = sorted((int(y) for y in years_raw), reverse=True) if years_raw else []
    rating = int(meta["rating"]) if meta.get("rating") else 0
    validate(path.relative_to(ROOT), meta, years, rating, tags_allowed)

    body = text[frontmatter.end():]
    marker = body.find(NOTES_MARKER)
    if marker != -1:
        body = body[marker + len(NOTES_MARKER):]
    notes = body.lstrip("\n") or NO_NOTES

    return Book(
        slug=path.stem,
        title=meta["title"],
        subtitle=meta.get("description", ""),
        author=meta["author"],
        narrator=meta.get("narrator", ""),
        format=meta.get("format", ""),
        shelf=meta["shelf"],
        years=years,
        rating=rating,
        tags=sorted(meta.get("tags", [])),
        notes=notes,
    )


def grid(cards: list[str]) -> str:
    """Wrap cards in the theme's own `.grid.cards` block — no custom CSS needed."""
    return '<div class="grid cards" markdown>\n\n' + "\n\n".join(cards) + "\n\n</div>"


def render_book_page(book: Book) -> str:
    """Rebuild a book's own page: frontmatter, then a generated heading and
    metadata card, then the notes the reader actually wrote, untouched.
    """
    fm = ['---', f'title: "{escape(book.title)}"']
    if book.subtitle:
        fm.append(f'description: "{escape(book.subtitle)}"')
    fm.append(f'author: "{escape(book.author)}"')
    if book.narrator:
        fm.append(f'narrator: "{escape(book.narrator)}"')
    if book.format:
        fm.append(f'format: {book.format}')
    fm.append(f'shelf: {book.shelf}')
    if book.shelf == READ:
        fm.append('read_years: [' + ", ".join(str(y) for y in book.years) + ']')
    if book.rating:
        fm.append(f'rating: {book.rating}')
    if book.tags:
        fm.append('tags: ' + quote_list(book.tags))
    # Zensical renders this next to the book in the sidebar.
    fm.append(f'icon: {book.icon}')
    fm.append('---')

    lines = fm + ['', f'# {book.heading_icon()} {markdown_escape(book.title)}']
    if book.subtitle:
        lines += ['', f'*{markdown_escape(book.subtitle)}*']

    details = [book.author_line()]
    if book.format:
        details.append(book.format_line())
    # No tooltip here: unlike the heading, the icon is spelled out beside it.
    details.append(f"{icon(SHELF_ICON[book.shelf])} {book.shelf_text()}")
    if book.rating:
        details.append(book.rating_line())

    card = "-   " + "<br>\n    ".join(details)
    lines += ['', grid([card]), '', NOTES_MARKER, '', book.notes.rstrip("\n") + "\n"]
    return "\n".join(lines)


def page(shelf: str, description: str, body: str) -> str:
    """Render a shelf page: frontmatter, heading, then whatever the shelf shows."""
    name, page_icon = SHELF_PAGE[shelf], SHELF_ICON[shelf]
    return (
        "---\n"
        f'title: "{name}"\n'
        f'description: "{description}"\n'
        f"icon: {page_icon}\n"
        "---\n"
        "\n"
        f"# {icon(page_icon)} {name}\n"
        "\n"
        f"{body}\n"
    )


def plural(count: int, singular: str, many: str) -> str:
    return f"{count} {singular if count == 1 else many}"


def stats(reading: list[Book], finished: list[Book], waiting: list[Book]) -> str:
    """The four counts at the top of the front page, as their own small cards."""
    listened = sum(1 for book in finished if book.format == "audiobook")
    counts = [
        (SHELF_ICON[READING], "On the nightstand", len(reading), "reading now"),
        (SHELF_ICON[READ], "Finished", len(finished), "read"),
        (SHELF_ICON[WANT], "Waiting on the shelf", len(waiting), "to read"),
        (FORMAT_ICON["audiobook"], "Listened to rather than read", listened, "listened to"),
    ]
    return grid([f"-   {icon(name, tooltip)} **{count}** {label}"
                 for name, tooltip, count, label in counts])


def render_pages(books: list[Book], tags_allowed: dict[str, str]) -> dict[Path, str]:
    reading = sorted((b for b in books if b.shelf == READING), key=lambda b: b.sort_key)
    finished = sorted((b for b in books if b.shelf == READ), key=lambda b: b.sort_key)
    waiting = sorted((b for b in books if b.shelf == WANT), key=lambda b: b.sort_key)
    years = sorted({year for book in finished for year in book.years}, reverse=True)

    reading_cards = grid(
        [b.card(subtitle=True, narrator=True, rule=True) for b in reading]
    )
    pages = {
        DOCS / "index.md": page(
            READING,
            "Books I'm reading right now.",
            stats(reading, finished, waiting) + "\n\n" + reading_cards,
        ),
        DOCS / "want-to-read.md": page(
            WANT,
            "Books waiting on the shelf.",
            f"{plural(len(waiting), 'book', 'books')} waiting "
            f"{'its' if len(waiting) == 1 else 'their'} turn.\n\n"
            + grid([b.card() for b in waiting]),
        ),
        PREVIOUSLY_READ / "index.md": previously_read_index(finished, years),
    }
    for book in books:
        pages[DOCS / f"{book.slug}.md"] = render_book_page(book)
    if ISSUE_FORM.exists():
        pages[ISSUE_FORM] = update_issue_form(tags_allowed)
    return pages


def breakdown(books: list[Book]) -> str:
    """How a year's books were read: `:lucide-headphones: 14 · :lucide-book-open: 6`."""
    counts = [
        ("audiobook", "%s %d listened to"),
        ("physical", "%s %d in print"),
    ]
    parts = []
    for book_format, template in counts:
        count = sum(1 for book in books if book.format == book_format)
        if count:
            parts.append(template % (icon(FORMAT_ICON[book_format]), count))
    return " · ".join(parts)


def previously_read_index(finished: list[Book], years: list[int]) -> str:
    """The Previously read page: every finished book, grouped under a year heading."""
    sections = []
    for year in years:
        of_year = sorted(
            (book for book in finished if year in book.years), key=lambda b: b.sort_key
        )
        sections.append("\n".join([
            f"## {year}",
            "",
            f"{plural(len(of_year), 'book', 'books')} finished · {breakdown(of_year)}",
            "",
            grid([book.card(prefix="../", rating=True) for book in of_year]),
        ]))

    if not years:
        span_phrase = ""
    elif len(years) > 1:
        span_phrase = f" between {years[-1]}–{years[0]}"
    else:
        span_phrase = f" in {years[0]}"

    return page(
        READ,
        "Every book I have finished.",
        f"{plural(len(finished), 'book', 'books')} finished{span_phrase}.\n\n"
        + "\n\n".join(sections),
    )


def render_nav(books: list[Book]) -> str:
    reading = sorted((b for b in books if b.shelf == READING), key=lambda b: b.sort_key)
    finished = sorted((b for b in books if b.shelf == READ), key=lambda b: b.sort_key)
    waiting = sorted((b for b in books if b.shelf == WANT), key=lambda b: b.sort_key)
    years = sorted({year for book in finished for year in book.years}, reverse=True)

    def entries(shelf: list[Book], prefix: str = "") -> list[str]:
        return [
            f'    {{ "{escape(book.title)}" = "{prefix}{book.slug}.md" }},'
            for book in shelf
        ]

    lines = ["nav = [", f'  {{ "{SHELF_PAGE[READING]}" = [', '    "index.md",']
    lines += entries(reading)
    lines += ["  ] },", f'  {{ "{SHELF_PAGE[READ]}" = [',
              '    "previously-read/index.md",']
    for year in years:
        # A re-read book is listed under the most recent year it was finished,
        # so it appears exactly once in the sidebar. The year itself is a
        # section header only — no page of its own.
        of_year = [book for book in finished if book.years[0] == year]
        lines.append(f'    {{ "{year}" = [')
        lines += [
            f'      {{ "{escape(book.title)}" = "{book.slug}.md" }},'
            for book in of_year
        ]
        lines.append("    ] },")
    lines += ["  ] },", f'  {{ "{SHELF_PAGE[WANT]}" = [', '    "want-to-read.md",']
    lines += entries(waiting)
    lines += ["  ] },", "]"]
    return "\n".join(lines) + "\n"


def escape(value: str) -> str:
    return value.replace("\\", "\\\\").replace('"', '\\"')


def update_config(nav: str) -> str:
    text = CONFIG.read_text(encoding="utf-8")
    start = text.index("nav = [")
    end = text.index("\n]\n", start) + len("\n]\n")
    return text[:start] + nav + text[end:]


def update_issue_form(tags_allowed: dict[str, str]) -> str:
    """Refill the tag checkboxes in the issue form from the vocabulary."""
    text = ISSUE_FORM.read_text(encoding="utf-8")
    matched = FORM_TAGS.search(text)
    if not matched:
        fail(f"{ISSUE_FORM.relative_to(ROOT)}: no generated tag block to fill")
    indent = matched.group(1)
    block = [f"{indent}# tags: generated by scripts/shelves.py"]
    block += [f"{indent}- label: {tag}" for tag in sorted(tags_allowed)]
    block += [f"{indent}# end tags", ""]
    return text[:matched.start()] + "\n".join(block) + text[matched.end():]


def stale_files() -> list[Path]:
    """Pages a previous run generated that this one no longer would."""
    legacy = sorted(LEGACY_TAGS.glob("*.md")) if LEGACY_TAGS.exists() else []
    return legacy


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="exit non-zero if anything is out of date, without writing",
    )
    args = parser.parse_args()

    tags_allowed = vocabulary()
    books = [parse_book(path, tags_allowed) for path in book_pages()]
    if not books:
        fail("no books found in docs/")

    outputs = render_pages(books, tags_allowed)
    outputs[CONFIG] = update_config(render_nav(books))

    stale = stale_files()
    for path in sorted(PREVIOUSLY_READ.glob("*.md")) if PREVIOUSLY_READ.exists() else []:
        if path not in outputs:
            stale.append(path)

    changed = [
        path
        for path, content in outputs.items()
        if not path.exists() or path.read_text(encoding="utf-8") != content
    ] + stale

    if args.check:
        for path in changed:
            print(f"out of date: {path.relative_to(ROOT)}")
        return 1 if changed else 0

    for path, content in outputs.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")
    for path in stale:
        path.unlink()
        if not any(path.parent.iterdir()):
            path.parent.rmdir()
    for path in outputs:
        if path in changed:
            print(f"updated: {path.relative_to(ROOT)}")
    for path in stale:
        print(f"removed: {path.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
